### PR TITLE
Updated Readme and added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by VaibhavArora314**
In this PR, I have
1. Updated README.md
2.  Created CONTRIBUTING.md

This is in reference to #1

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
hey @aakzsh, can you pls look into this

**Comment by aakzsh** [comment]
Hey @VaibhavArora314, in point 2 in contributing md, there's a typo, should be "fork", and please put the link as
https://github.com/forkedusername/GDSC-USICT-flutter-projects

**Comment by VaibhavArora314** [comment]
Done @aakzsh

**Comment by aakzsh** [comment]
great 🚀

**Pull request merged**
